### ISSUE TITLE
[FEATURE] Create a header with navigation

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#1]
As a user I want to see a header with a navigationbar on the homepage.

The header and its child components are created using semantic HTML. The header contains a navigation bar.

**Acceptance criteria (AC)**

- [ ] Under the pages folder, create a folder called **components**
- [ ] Create a file called **Header.js**
- [ ] Create a header using full with of the device
- [ ] The header has a height of 80px
- [ ] Inside the header is a navigationbar created using semantic HTML
- [ ] Name the links Home and Courses
- [ ] The links have a font size of 16px
- [ ] use only as much as CSS needed so that the Links are next to each other and are not underlined. Spacing is not important.

**Wireframe**
![Wireframe of header showing two links inside navigation bar](https://github.com/YurisCodingClub/accessibility-mentor/assets/54622834/e3d5250f-53cc-4b14-ae14-90f12170aefe)

**Note**
If you are a complete beginner in coding or open source, don't worry. Let's start with the following:
Look up what semantic HTML means.
Think about what a navigation actually is (a list of links). Use the corresponding semantic HTML for it.
You can find everything needed to fulfill this issue by looking the terms up in [w3schools](https://www.w3schools.com) or [MDN](https://developer.mozilla.org/en-US/). If these sites are new to you, don't worry. You will get used to them over time.
Happy coding 🙂

**Comment by Roar022** [comment]
I would like to work on this issue.Please assign this issue to me.

**Comment by Vaishali785** [comment]
Hi @YuriDevAT , I know HTML very well and I'm trying to participate in hacktoberfest. Can you please assign this issue to me?

**Comment by YuriDevAT** [comment]
> Hi @YuriDevAT , I know HTML very well and I'm trying to participate in hacktoberfest. Can you please assign this issue to me?

Create, to have you on the team, Vaishali. I will assign you on October 1st, when Hacktoberfest officially starts.

**Comment by avyuktsoni0731** [comment]
Hi @YuriDevAT . Can i please get this issue assigned to me? I have already completed the assignment, but got my merge request rejected because it was not "ready to dev".

**Comment by YuriDevAT** [comment]
> Hi @YuriDevAT . Can i please get this issue assigned to me? I have already completed the assignment, but got my merge request rejected because it was not "ready to dev". 
> 
> Thank u :)

Hi @avyuktsoni0731  Please read the contribution guideline thoroughly. Do not create a PR when the issue is not assigned to you, it will not get accepted. Someone is already working on it.

**Comment by Vaishali785** [comment]
Hi @YuriDevAT this task is assigned to me, and I've created the PR. Please review and merge it.
