### ISSUE TITLE
[FEATURE] Add Storybook to the project

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#14]
Install Storybook to the project following the official documentation https://storybook.js.org/

**Acceptance criteria**
- [ ] The latest version of Storybook is installed

**Comment by hariscs** [comment]
now i think i can work on this @YuriDevAT 😅

**Comment by YuriDevAT** [comment]
Thanks for your patience, @hariscs 💟 I am always happy to have you contributing to one of my projects. I am trying my best to add as many issues as possible in the next few days.
