### ISSUE TITLE
[FEATURE] Add footer

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#16]
As a user, I want to see a footer containing the logo of the organisation.

**Acceptance criteria (AC)**

- [ ] Under the pages folder, create a folder called components
- [ ] Create a file called Footer.js
- [ ] Create a footer using full with of the device
- [ ] Footer showing on bottom of the page
- [ ] Logo is showing in the footer
- [ ] a copyright section is added below
- [ ] No additional styling needed

**Wireframe**
![Footer](https://github.com/YurisCodingClub/accessibility-mentor/assets/54622834/ffd7903b-1a73-4c81-b237-08696fc3c703)

**Logo**
![logo](https://github.com/YurisCodingClub/accessibility-mentor/assets/54622834/82521830-4828-4ea1-bc07-2303f99622ce)

**Comment by joshijoe05** [comment]
Hello, I would ilke to work on this issue, Please assign this to me

**Comment by SohamTamhane** [comment]
Hi, Greeting of the Day.
Can you please assign this issue to me?

**Comment by avyuktsoni0731** [comment]
Hi @YuriDevAT . I am willing to work on this assignment, can i please get this assigned to me? 

Thanks

**Comment by Arya-n-101** [comment]
hi @YuriDevAT . It would be great if you assign this to me.Looking forward to work with you.

**Comment by CBID2** [comment]
Hi @YuriDevAT! :) I had a great time creating the issue template! :) Now, I haven’t been coding lately and this issue would be a great way to start again. So, can I be assigned to it please?

**Comment by YuriDevAT** [comment]
Glad to hear. Please go ahead and have some fun coding @CBID2 😁

**Comment by AviGawande** [comment]
@YuriDevAT  want to work on this repo

**Comment by CBID2** [comment]
> @YuriDevAT want to work on this repo

Hi @AviGawande. I'm workin on this issue.
