### ISSUE TITLE
[FEATURE] Create Card Component

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#27]
### Description
Create a card component using storybook. Do research on typical horizontal card styling (height, width, padding,..) by checking out common frameworks like [MUI](https://mui.com/material-ui/) or Bootstrap.

![card](https://github.com/YurisCodingClub/accessibility-mentor/assets/54622834/56a07b48-a8a9-458c-94a7-1d6f3cd3b783)

### Additional links
Official docs from storybook https://storybook.js.org/

```[tasklist]
### Tasks
- [ ] Creade card component
- [ ] Use dummy image and text
```

**Comment by TaylorDJones11** [comment]
Hi @YuriDevAT ! I'm still quite new to open-source but familiar with working with NextJs & would love to work on this issue ☺️

**Comment by YuriDevAT** [comment]
Happy to have you on the team, @TaylorDJones11 😄

**Comment by TaylorDJones11** [comment]
@YuriDevAT looking over the code, should my set up be similar to the "stories" directory or "components" 
<img width="162" alt="Screenshot 2023-10-14 at 13 10 28" src="https://github.com/YurisCodingClub/accessibility-mentor/assets/72883059/8b39b6f4-eb4a-46c3-bcb3-e5cfe362167e">
<img width="158" alt="Screenshot 2023-10-14 at 13 10 38" src="https://github.com/YurisCodingClub/accessibility-mentor/assets/72883059/71dd629e-8f58-4045-92ab-0a0a2d1440a9">

**Comment by YuriDevAT** [comment]
Thanks for your question @TaylorDJones11. As far as I understand how storybook works is to create a component as a "story" as they call it. These are stored in the stories folder
<img width="140" alt="Stories folder" src="https://github.com/YurisCodingClub/accessibility-mentor/assets/54622834/27eb6e8c-0949-4ea3-9689-5e3cc59725f6">
There are already a few premade components in it. As you can see in the folder structure, a button component consists of three files: `Button.js`, `Button.stories.js` and `button.css`.

To see the storybook of AccessibilityMentor locally, you have to run `npm run storybook`, then it will be opened in localhost:6006.

**Comment by TaylorDJones11** [comment]
> Thanks for your question @TaylorDJones11. As far as I understand how storybook works is to create a component as a "story" as they call it. These are stored in the stories folder <img alt="Stories folder" width="140" src="https://user-images.githubusercontent.com/54622834/275236951-27eb6e8c-0949-4ea3-9689-5e3cc59725f6.png"> There are already a few premade components in it. As you can see in the folder structure, a button component consists of three files: `Button.js`, `Button.stories.js` and `button.css`.
> 
> To see the storybook of AccessibilityMentor locally, you have to run `npm run storybook`, then it will be opened in localhost:6006.

Great, thanks!
