### ISSUE TITLE
[FEATURE] Create Button component

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#28]
### Description
Create a button component using storybook. Do research on typical button styling (height, width, padding,..) by checking out common frameworks like [MUI](https://mui.com/material-ui/) or Bootstrap.

![button](https://github.com/YurisCodingClub/accessibility-mentor/assets/54622834/8b32d844-109b-4ca3-bd57-c2ba5cbd45a5)

### Additional links
Official docs from storybook https://storybook.js.org/
```[tasklist]
### Tasks
- [x] Create Button component
```

**Comment by zakariyahrobiat** [comment]
@YuriDevAT please assign this task to me

**Comment by YuriDevAT** [comment]
Happy to have you contributing @zakariyahrobiat 😄

**Comment by YuriDevAT** [comment]
Hi @zakariyahrobiat. It has been two weeks. Are you working on this? Otherwise I will assign it to another contributor since as mentioned in the contribution guide issues should have progress within 2 weeks.
