### ISSUE TITLE
[FEATURE] Create router 

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#39]
Description
Currently, both components are showing in the app when loading, the `<Content />` and the `<Hero />`.

Create a router, that, when the homepage shows the `<Hero />` component (as well as when clicking on Home in the navigation bar), and when clicking on Courses, the `<Content />` component is showing.

```[tasklist]
### Tasks
- [ ] Implement routing for Home and Courses
```

**Note:** Decide if you are going to use Next routing system or the new react-router. Explain why in the PR.

**Comment by aryankshl** [comment]
hey @YuriDevAT can you assign this to me?

**Comment by Pramod3245** [comment]
Hello @YuriDevAT I have figured how to do it. Instead of having another separate directory for the components if we move it under the pages directory and use the Next Js router we can achieve it.

**Comment by Ahsankhalid618** [comment]
I'll do it
