### ISSUE TITLE
[FEATURE] Issue template bug

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#4]
As a contributor, I want to choose between pre-made templates to create an issue for the repository.

**Acceptance Criteria (AC)**

- [ ] in the .github folder create a folder called **ISSUE_TEMPLATE**
- [ ] in the folder ISSUE_TEMPLATE create a file called bug.yml
- [ ] for the name use: 🐛 Bug
- [ ] for the description use: Report an issue to help improve the project.
- [ ] for the labels use: ["🛠 goal: fix"]
- [ ] in the body, add three type textarea
- [ ] each of these textarea has an unique id, description, screenshots and extrainfo
- [ ] each type has 2 attributes: a label and a description. Come up with own text **Hint** look in other repositories which uses issue templates to get inspiration what to write
- [ ] each type has a validations, set to true for the description and false to screenshots and extrainfo

**Useful link**
Official docs on how to create a template 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by ehammes** [comment]
Hi @YuriDevAT, can I work on this issue? Thanks

**Comment by YuriDevAT** [comment]
Happy to have to as a contributor, @ehammes 😄

**Comment by YuriDevAT** [comment]
Hi @ehammes are you working on this? As mentioned in the contribution guide contributors get unassigned after two weeks when nothing happens to give other contributors the chance to work on it.

**Comment by ehammes** [comment]
@YuriDevAT Yes, apologies on the delay, I'll get it completed this weekend

**Comment by ehammes** [comment]
@YuriDevAT PR #46 ready for review
