### ISSUE TITLE
BUG: the contribution guidelines are incorrect

### ISSUE THREAD

**Issue by ArslanYM** [YurisCodingClub/accessibility-mentor#43]
Tried to run the app locally while following the contribution guideline steps. Doesnt seem to work properly.
![issue](https://github.com/YurisCodingClub/accessibility-mentor/assets/104521101/15201a10-7c0c-46be-9363-7869ac0b04e9)

**Comment by YuriDevAT** [comment]
Can you share all the steps you have taken and which contribution guideline you are referring to? It seems like you have not installed the dependecies which is **[step number 4](https://github.com/YurisCodingClub/accessibility-mentor#commands)** of the guide mentioned in the README of the project.

### Prerequisites

Before contributing or adding a new feature, please make sure you have already installed the following tools:
- [NodeJs](https://nodejs.org/en/download)
- 
### Commands

1. Create a fork of the project to get your own copy
2. `git clone https://github.com/YurisCodingClub/accessibility-mentor.git` - to get the code locally
3. `cd accessibility-mentor` - to navigate into the project
4. `npm install` - to install all the dependencies
5. `code .` - to open Visual Studio Code
6. `npm run dev` - to get the project running
7. `npm run storybook` - to open storybook in localhost:6006

**Comment by ArslanYM** [comment]
@YuriDevAT 

> Can you share all the steps you have taken and which contribution guideline you are referring to? It seems like you have not installed the dependecies which is **[step number 4](https://github.com/YurisCodingClub/accessibility-mentor#commands)** of the guide mentioned in the README of the project.
> 
> ### Prerequisites
> Before contributing or adding a new feature, please make sure you have already installed the following tools:
> 
> * [NodeJs](https://nodejs.org/en/download)
> 
> ### Commands
> 1. Create a fork of the project to get your own copy
> 2. `git clone https://github.com/YurisCodingClub/accessibility-mentor.git` - to get the code locally
> 3. `cd accessibility-mentor` - to navigate into the project
> 4. `npm install` - to install all the dependencies
> 5. `code .` - to open Visual Studio Code
> 6. `npm run dev` - to get the project running
> 7. `npm run storybook` - to open storybook in localhost:6006

Actually I did run `npm install` the first time, the actual issue is that you are running this app on 18.3.0 node version and it is not compatible with the latest version. To solve this i had to use nvm to degrade to a lower version and then it worked.
