### ISSUE TITLE
[FEATURE] Issue template docs

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#5]
As a contributor, I want to choose between pre-made templates to create an issue for the repository.

**Acceptance Criteria (AC)**

- [ ] in the .github folder create a folder called **ISSUE_TEMPLATE**
- [ ] in the folder ISSUE_TEMPLATE create a file called docs.yml
- [ ] for the name use: 📄 Documentation issue
- [ ] for the description use: Found an issue in the documentation? You can use this one!
- [ ] for the labels use: ["📄 aspect: text"]
- [ ] in the body, add three type textarea
- [ ] each of these textarea has an unique id, description, screenshots and extrainfo
- [ ] each type has 2 attributes: a label and a description. Come up with own text. **Hint** look in other repositories which uses issue templates to get inspiration what to write
- [ ] each type has a validations, set to true for the description and false to screenshots and extrainfo

**Useful link**
Official docs on how to create a template 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by CBID2** [comment]
Hi @YuriDevAT! :) Can I work on this issue?

**Comment by MuaviyaImran** [comment]
Hi @YuriDevAT
I am new to open source contribution community. Can i work on it? Kindly Assign this issue to me.

**Comment by YuriDevAT** [comment]
Happy to have you contributing to the project @CBID2 😄

**Comment by CBID2** [comment]
> Happy to have you contributing to the project @CBID2 😄

Done with my PR @YuriDevAT!  It's #24
