### ISSUE TITLE
[BUG] FEATURE issue template  does not appear

### ISSUE THREAD

**Issue by CBID2** [YurisCodingClub/accessibility-mentor#52]
When raising an issue, the template for [FEATURE] does not appear, even though the `feature.yml` file is in the code base.

### Error message
<img width="1424" alt="Error message for feature.yml" src="https://github.com/YurisCodingClub/accessibility-mentor/assets/54622834/64d2ddb2-aa4e-43ec-8ba3-bb52746c7ced">

### Links mentioned in the message
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#input-is-not-a-permitted-key
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-required-attribute-key-value-is-missing
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-x-is-not-a-permitted-key

### Expected output
The `bug.yml` and `other.yml` template appear as expected.

<img width="1265" alt="Issue template appearance" src="https://github.com/YurisCodingClub/accessibility-mentor/assets/54622834/3fcbffa9-ee1e-4fa3-ba51-b8dbd5c3294d">

```[tasklist]
### Tasks
- [ ] Update the content of the `feature.yml` file 
- [ ] if uncertain, compare with the two yml files which are working (`bug.yml`, `other.yml`)
```

**Comment by Jaivignesh-afk** [comment]
I apologize for not noticing that someone was already assigned to this issue. I have closed the PR now. If it's acceptable, I would be more than willing to assist with this issue.

**Comment by CBID2** [comment]
> I apologize for not noticing that someone was already assigned to this issue. I have closed the PR now. If it's acceptable, I would be more than willing to assist with this issue.

This issue is free for the taking @Jaivignesh-afk: https://github.com/YurisCodingClub/accessibility-mentor/issues/31

**Comment by Jaivignesh-afk** [comment]
i have re-opened my PR,Please review!!!

**Comment by CBID2** [comment]
> i have re-opened my PR,Please review!!!

I've been assigned to this issue @Jaivignesh-afk

**Comment by Jaivignesh-afk** [comment]
I apologize for my misunderstanding.I will try to work on issue#31.Thank you @CBID2
