### ISSUE TITLE
[FEATURE] Issue template feature

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#6]
As a contributor, I want to choose between pre-made templates to create an issue for the repository.

**Acceptance Criteria (AC)**

- [ ] in the .github folder create a folder called **ISSUE_TEMPLATE**
- [ ] in the folder ISSUE_TEMPLATE create a file called **feature.yml**
- [ ] for the name use: 💡 Feature Request
- [ ] for the description use: Have a new idea/feature? Please suggest!
- [ ] for the labels use: ["⭐ goal: addition"]
- [ ] in the body, add three type textarea
- [ ] each of these textarea has an unique id, description, screenshots and extrainfo
- [ ] each type has 2 attributes: a label and a description. Come up with own text. **Hint** look in other repositories which uses issue templates to get inspiration what to write
- [ ] each type has a validations, set to true for the description and false to screenshots and extrainfo

**Useful link**
Official docs on how to create a template 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by hariscs** [comment]
Let me work on all these templates @YuriDevAT 🙌

**Comment by YuriDevAT** [comment]
Thanks @hariscs for your interest. You are way too experienced for the "good first issue" labeled ones. 😉 let's keep those for beginners and first timers.

Hopefully, there are other issues you are interested in. 😇

**Comment by hariscs** [comment]
I thought CI/CD was not for beginners + there wasn't any other issues 😅
Open for any other complex issues or if someone need any help 🙌

**Comment by aliakhizer** [comment]
Hi @YuriDevAT, im a first-time open-source contributor, kindly assign this to me.

**Comment by YuriDevAT** [comment]
Sure @aliakhizer please go ahead.
