### ISSUE TITLE
[FEATURE] Issue template other

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#7]
As a contributor, I want to choose between pre-made templates to create an issue for the repository.

**Acceptance Criteria (AC)**

- [ ] in the .github folder create a folder called **ISSUE_TEMPLATE**
- [ ] in the folder ISSUE_TEMPLATE create a file called **other.yml**
- [ ] for the name use: Other
- [ ] for the description use: Use this for any other issues. Please do NOT create blank issues!
- [ ] for the labels use: ["🚦 status: awaiting triage"]
- [ ] in the body, add a type markdown with an attributes containing a value "# Other issue"
- [ ] in the body, add two type textarea
- [ ] each of these textarea has an unique id: description and extrainfo
- [ ] each textarea type has 2 attributes: a label and a description. Come up with own text. **Hint** look in other repositories which uses issue templates to get inspiration what to write
- [ ] each textarea type has a validations, set to true for the description and false to extrainfo

**Useful link**
Official docs on how to create a template
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by MuaviyaImran** [comment]
Hi @YuriDevAT
I am new to open source contribution community. Can i work on it? Kindly Assign this issue to me.

**Comment by Pinaka-Pani-18** [comment]
Hi, I have experience in creating these issue templates. Can you please assign them to me?

**Comment by YuriDevAT** [comment]
Sure, go ahead @Pinaka-Pani-18

**Comment by YuriDevAT** [comment]
Hi @Pinaka-Pani-18 are you still working on this? As mentioned in the contribution guidelines the contributor gets unassigned after two weeks when nothing happened.
