### ISSUE TITLE
[FEATURE] Create a hero section

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#9]
As a user I want to see a hero section showing intro text on the left and an image/graphic on the right to be able to understand what the application is about.

**Acceptance criteria (AC)**

- [ ] The section should be about 80% of the screen height
- [ ] The section should have a background color HEX #f5f5f5 the whole with
- [ ] The content should cover 80% of the width
- [ ] The text content contains a short header followed by an paragraph 3-4 lines long (lorem ipsum)
- [ ] Use semantic HTML
- [ ] Use default styling for the text, no CSS needed
- [ ] Use a random image/graphic

![Home - Hero wireframe](https://github.com/YurisCodingClub/accessibility-mentor/assets/54622834/1765c6a4-5a34-4bba-86a0-2de2f7da82df)

**Comment by stktyagi** [comment]
I want to contribute and resolve this issue for hacktoberfest. Kindly assign me this issue. Thanks a lot!

**Comment by Pinaka-Pani-18** [comment]
Hi, can I work on this issue ?

**Comment by Salamah-Jimoh** [comment]
Hi, I want this to be assigned to me. Thank you

**Comment by dark-developer15** [comment]
Hey @YuriDevAT, I have almost completed this issue but since it is not assigned to me, I will not making the PR, can I get assigned to it.

**Comment by YuriDevAT** [comment]
Happy to have you contributing to the project @Salamah-Jimoh 😄

**Comment by shreyanshig** [comment]
Could you please this task to me
